#Q1 Write a Python program to create an array of 5 integers and display the array
Access individual element through indexes

In [24]:
a=np.array([1,7,8,4,3])
print("Array:",a)
for i in a:
    print(i)

Array: [1 7 8 4 3]
1
7
8
4
3


#Q2 Write a Python program to reverse the order of the items in the array

In [30]:
a=np.array([2,-1,7,5,22,8,55,0,5,3])
print("Original array is:",a)
b=a[::-1]
print("Reversed array is: ",b)

Original array is: [ 2 -1  7  5 22  8 55  0  5  3]
Reversed array is:  [ 3  5  0 55  8 22  5  7 -1  2]


#Q3 Create a 4X2 integer array and Prints its attributes
#The shape of an array.
#Array dimensions.
#The Length of each element of the array in bytes.

In [61]:
a=np.array([[4,0],[3,1],[9,0],[2,5]])
print("Array is: \n",a)
print("Shape of an array is: ",a.shape)
print("Dimensions of array is" ,a.ndim)
print("Length of each element of the array is: ",a.nbytes)

Array is: 
 [[4 0]
 [3 1]
 [9 0]
 [2 5]]
Shape of an array is:  (4, 2)
Dimensions of array is 2
Length of each element of the array is:  32


#Q4 return array of items in the third column from all rows in the following nump
([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [69]:
a=np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print("Array is: \n",a)
thirdRow=a[...,2]
print("Array with third column from all rows is: \n",thirdRow)

Array is: 
 [[11 22 33]
 [44 55 66]
 [77 88 99]]
Array with third column from all rows is: 
 [33 66 99]


#Q5 Create a result array by adding the following two NumPy arrays
#arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
#arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [73]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
addArray=arrayOne+arrayTwo
print("Addition of both numpy array is: \n",addArray)
subArray=arrayOne-arrayTwo
print("Subtraction of both numpy array is: \n",subArray)
multiArray=arrayOne*arrayTwo
print("Multiplication of both numpy array is: \n",multiArray)

[[ 5  6  9]
 [21 18 27]]
Addition of both numpy array is: 
 [[20 39 33]
 [25 25 28]]
Subtraction of both numpy array is: 
 [[-10 -27 -15]
 [ 17  11  26]]
Multiplication of both numpy array is: 
 [[ 75 198 216]
 [ 84 126  27]]


#Q6 Sort the previous array

In [55]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
print("Original array is: \n",arrayOne)
print("Sorted array is: \n", np.sort(arrayOne))
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
print("Original array is: \n",arrayTwo)
print("Sorted array is: \n", np.sort(arrayTwo))

Original array is: 
 [[ 5  6  9]
 [21 18 27]]
Sorted array is: 
 [[ 5  6  9]
 [18 21 27]]
Original array is: 
 [[15 33 24]
 [ 4  7  1]]
Sorted array is: 
 [[15 24 33]
 [ 1  4  7]]


In [77]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1],[3,4,5]])
print("First array is: \n",arrayOne)
print("Second array is: \n",arrayTwo)
dotArray=np.dot(arrayOne,arrayTwo)
print("Dot product of both array is : \n",dotArray)

First array is: 
 [[ 5  6  9]
 [21 18 27]]
Second array is: 
 [[15 33 24]
 [ 4  7  1]
 [ 3  4  5]]
Dot product of both array is : 
 [[126 243 171]
 [468 927 657]]
